//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Domain {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActionType {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionType() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.Domain.ActionType", typeof(ActionType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        public static string How_to_use_this_page_ {
            get {
                return ResourceManager.GetString("How to use this page?", resourceCulture);
            }
        }
        
        public static string Got_it {
            get {
                return ResourceManager.GetString("Got it", resourceCulture);
            }
        }
        
        public static string Suppliers {
            get {
                return ResourceManager.GetString("Suppliers", resourceCulture);
            }
        }
        
        public static string Browse_and_manage_all_available_suppliers {
            get {
                return ResourceManager.GetString("Browse and manage all available suppliers", resourceCulture);
            }
        }
        
        public static string New_supplier {
            get {
                return ResourceManager.GetString("New supplier", resourceCulture);
            }
        }
        
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string No_suppliers_found_ {
            get {
                return ResourceManager.GetString("No suppliers found ", resourceCulture);
            }
        }
        
        public static string Edit_supplier {
            get {
                return ResourceManager.GetString("Edit supplier", resourceCulture);
            }
        }
        
        public static string Create_new_supplier {
            get {
                return ResourceManager.GetString("Create new supplier", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Products_by {
            get {
                return ResourceManager.GetString("Products by", resourceCulture);
            }
        }
        
        public static string No_products_found_for_this_supplier {
            get {
                return ResourceManager.GetString("No products found for this supplier", resourceCulture);
            }
        }
        
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string Browse_and_manage_all_available_products {
            get {
                return ResourceManager.GetString("Browse and manage all available products", resourceCulture);
            }
        }
        
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        public static string All_categories {
            get {
                return ResourceManager.GetString("All categories", resourceCulture);
            }
        }
        
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        public static string All_suppliers {
            get {
                return ResourceManager.GetString("All suppliers", resourceCulture);
            }
        }
        
        public static string New_product {
            get {
                return ResourceManager.GetString("New product", resourceCulture);
            }
        }
        
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        public static string No_products_found {
            get {
                return ResourceManager.GetString("No products found", resourceCulture);
            }
        }
        
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        public static string Volume_unit {
            get {
                return ResourceManager.GetString("Volume unit", resourceCulture);
            }
        }
        
        public static string Edit_product {
            get {
                return ResourceManager.GetString("Edit product", resourceCulture);
            }
        }
        
        public static string Create_new_product {
            get {
                return ResourceManager.GetString("Create new product", resourceCulture);
            }
        }
        
        public static string Is_component__used_in_recipes_ {
            get {
                return ResourceManager.GetString("Is component (used in recipes)", resourceCulture);
            }
        }
        
        public static string Storage_rooms {
            get {
                return ResourceManager.GetString("Storage rooms", resourceCulture);
            }
        }
        
        public static string New_storage_room {
            get {
                return ResourceManager.GetString("New storage room", resourceCulture);
            }
        }
        
        public static string Write_off_statistics {
            get {
                return ResourceManager.GetString("Write-off statistics", resourceCulture);
            }
        }
        
        public static string No_storage_rooms_found {
            get {
                return ResourceManager.GetString("No storage rooms found", resourceCulture);
            }
        }
        
        public static string Edits_storage_room {
            get {
                return ResourceManager.GetString("Edits storage room", resourceCulture);
            }
        }
        
        public static string Create_new_storage_room {
            get {
                return ResourceManager.GetString("Create new storage room", resourceCulture);
            }
        }
        
        public static string Select_address {
            get {
                return ResourceManager.GetString("Select address", resourceCulture);
            }
        }
        
        public static string Allowed_roles__comma_separated_ {
            get {
                return ResourceManager.GetString("Allowed roles (comma-separated)", resourceCulture);
            }
        }
        
        public static string Tip__leave_empty_to_allow_no_roles__or_handle_at_backend_as_needed_ {
            get {
                return ResourceManager.GetString("Tip: leave empty to allow no roles (or handle at backend as needed)", resourceCulture);
            }
        }
        
        public static string Monthly_statistics {
            get {
                return ResourceManager.GetString("Monthly statistics", resourceCulture);
            }
        }
        
        public static string Removed_product_quantities_per_month {
            get {
                return ResourceManager.GetString("Removed product quantities per month", resourceCulture);
            }
        }
        
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        public static string All_days {
            get {
                return ResourceManager.GetString("All days", resourceCulture);
            }
        }
        
        public static string Columns {
            get {
                return ResourceManager.GetString("Columns", resourceCulture);
            }
        }
        
        public static string Export_Excel {
            get {
                return ResourceManager.GetString("Export Excel", resourceCulture);
            }
        }
        
        public static string Removed_quantity {
            get {
                return ResourceManager.GetString("Removed quantity", resourceCulture);
            }
        }
        
        public static string Removed_volume {
            get {
                return ResourceManager.GetString("Removed volume", resourceCulture);
            }
        }
        
        public static string No_data_to_display {
            get {
                return ResourceManager.GetString("No data to display", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Manage_reference_data___components___all_in_one_place {
            get {
                return ResourceManager.GetString("Manage reference data & components - all in one place", resourceCulture);
            }
        }
        
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        public static string New_component {
            get {
                return ResourceManager.GetString("New component", resourceCulture);
            }
        }
        
        public static string Edit_actionType {
            get {
                return ResourceManager.GetString("Edit actionType", resourceCulture);
            }
        }
        
        public static string Create_new_actionType {
            get {
                return ResourceManager.GetString("Create new actionType", resourceCulture);
            }
        }
        
        public static string Edit_reason {
            get {
                return ResourceManager.GetString("Edit reason", resourceCulture);
            }
        }
        
        public static string Create_new_reason {
            get {
                return ResourceManager.GetString("Create new reason", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string Edit_productCategory {
            get {
                return ResourceManager.GetString("Edit productCategory", resourceCulture);
            }
        }
        
        public static string Create_new_productCategory {
            get {
                return ResourceManager.GetString("Create new productCategory", resourceCulture);
            }
        }
        
        public static string Edit_address {
            get {
                return ResourceManager.GetString("Edit address", resourceCulture);
            }
        }
        
        public static string Create_new_address {
            get {
                return ResourceManager.GetString("Create new address", resourceCulture);
            }
        }
        
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        public static string Building_nr {
            get {
                return ResourceManager.GetString("Building nr", resourceCulture);
            }
        }
        
        public static string Unit_nr {
            get {
                return ResourceManager.GetString("Unit nr", resourceCulture);
            }
        }
        
        public static string Postal_code {
            get {
                return ResourceManager.GetString("Postal code", resourceCulture);
            }
        }
        
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        public static string Recipe_product {
            get {
                return ResourceManager.GetString("Recipe product", resourceCulture);
            }
        }
        
        public static string Component_product {
            get {
                return ResourceManager.GetString("Component product", resourceCulture);
            }
        }
        
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        public static string Discard_items {
            get {
                return ResourceManager.GetString("Discard items", resourceCulture);
            }
        }
        
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        public static string Action_type {
            get {
                return ResourceManager.GetString("Action type", resourceCulture);
            }
        }
        
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        public static string Storage_room {
            get {
                return ResourceManager.GetString("Storage room", resourceCulture);
            }
        }
        
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        public static string Declined {
            get {
                return ResourceManager.GetString("Declined", resourceCulture);
            }
        }
        
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        public static string All_users {
            get {
                return ResourceManager.GetString("All users", resourceCulture);
            }
        }
        
        public static string All_months {
            get {
                return ResourceManager.GetString("All months", resourceCulture);
            }
        }
        
        public static string All_years {
            get {
                return ResourceManager.GetString("All years", resourceCulture);
            }
        }
        
        public static string Dispose_item {
            get {
                return ResourceManager.GetString("Dispose item", resourceCulture);
            }
        }
        
        public static string Requested_by {
            get {
                return ResourceManager.GetString("Requested by", resourceCulture);
            }
        }
        
        public static string Requested_at {
            get {
                return ResourceManager.GetString("Requested at", resourceCulture);
            }
        }
        
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        public static string Users_and_roles {
            get {
                return ResourceManager.GetString("Users and roles", resourceCulture);
            }
        }
        
        public static string View_users_and_manage_their_roles {
            get {
                return ResourceManager.GetString("View users and manage their roles", resourceCulture);
            }
        }
        
        public static string Full_name {
            get {
                return ResourceManager.GetString("Full name", resourceCulture);
            }
        }
        
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string Account_info {
            get {
                return ResourceManager.GetString("Account info", resourceCulture);
            }
        }
        
        public static string View_selected_user_profile {
            get {
                return ResourceManager.GetString("View selected user profile", resourceCulture);
            }
        }
        
        public static string User_details {
            get {
                return ResourceManager.GetString("User details", resourceCulture);
            }
        }
        
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Create_a_new_account {
            get {
                return ResourceManager.GetString("Create a new account", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Role_name {
            get {
                return ResourceManager.GetString("Role name", resourceCulture);
            }
        }
        
        public static string Manage_access_roles_for_your_system {
            get {
                return ResourceManager.GetString("Manage access roles for your system", resourceCulture);
            }
        }
        
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        public static string Confirm_new_password {
            get {
                return ResourceManager.GetString("Confirm new password", resourceCulture);
            }
        }
        
        public static string Enter_new_password {
            get {
                return ResourceManager.GetString("Enter new password", resourceCulture);
            }
        }
        
        public static string Enter_current_password {
            get {
                return ResourceManager.GetString("Enter current password", resourceCulture);
            }
        }
        
        public static string Update_your_password_securely {
            get {
                return ResourceManager.GetString("Update your password securely", resourceCulture);
            }
        }
        
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        public static string Select_role {
            get {
                return ResourceManager.GetString("Select role", resourceCulture);
            }
        }
        
        public static string Select_user {
            get {
                return ResourceManager.GetString("Select user", resourceCulture);
            }
        }
        
        public static string Select_a_user_and_assign_a_role {
            get {
                return ResourceManager.GetString("Select a user and assign a role", resourceCulture);
            }
        }
        
        public static string Assign_role_to_user {
            get {
                return ResourceManager.GetString("Assign role to user", resourceCulture);
            }
        }
        
        public static string Save_data {
            get {
                return ResourceManager.GetString("Save data", resourceCulture);
            }
        }
        
        public static string View_and_update_your_profile {
            get {
                return ResourceManager.GetString("View and update your profile", resourceCulture);
            }
        }
        
        public static string My_account {
            get {
                return ResourceManager.GetString("My account", resourceCulture);
            }
        }
        
        public static string No_users_found {
            get {
                return ResourceManager.GetString("No users found", resourceCulture);
            }
        }
        
        public static string No_data_found {
            get {
                return ResourceManager.GetString("No data found", resourceCulture);
            }
        }
        
        public static string Most_active_removers_ {
            get {
                return ResourceManager.GetString("Most active removers ", resourceCulture);
            }
        }
        
        public static string Most_removed_products {
            get {
                return ResourceManager.GetString("Most removed products", resourceCulture);
            }
        }
        
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        public static string Discarded_most_often {
            get {
                return ResourceManager.GetString("Discarded most often", resourceCulture);
            }
        }
        
        public static string No_problematic_products_found {
            get {
                return ResourceManager.GetString("No problematic products found", resourceCulture);
            }
        }
        
        public static string Pending_discards {
            get {
                return ResourceManager.GetString("Pending discards", resourceCulture);
            }
        }
        
        public static string No_pending_actions {
            get {
                return ResourceManager.GetString("No pending actions", resourceCulture);
            }
        }
        
        public static string View_all {
            get {
                return ResourceManager.GetString("View all", resourceCulture);
            }
        }
    }
}
